#!/bin/bash

opath=$PATH
PATH=/bin:/usr/bin

case $# in
	0|1|2) echo 'Usage xmlParser field value file' 1>&2; exit 1
esac

awk -v field=$1 -v value=$2 '
	BEGIN {FS = "="}
	{
		if($1 == field)
		{ 
			printf "%s=\"%s\"\n",$1,value }
		else {
			print
		}
	}
' $3